### ISSUE TITLE
Users can't see Virtual Network and Security Group names

### ISSUE THREAD

**Issue by BcTpe4HbIu** [OpenNebula/one#2223]
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [ ] 5.4.6
- [ ] 5.4.7
- [ ] 5.4.8
- [ ] 5.4.9
- [ ] 5.4.10
- [ ] 5.4.11
- [X] 5.4.12
- [X] 5.4.13
- [ ] 5.4.14
- [ ] 5.4.15
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [X] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

In fresh install normal users (not members of oneadmin group) see only ID and Group fields in Virtual Netwroks and Security Groups tables.

### Expected Behavior
Users shoud be able to see network name

### Actual Behavior
Users see only ID and Group

## How to reproduce

1. Create group
2. Create user
3. Make user admin for a group
4. Login as user and check Network -> Virtual Networks

Same thing in VM instantiate dialog when chosing network.

![2018-06-26 13-52-21](https://user-images.githubusercontent.com/4357087/41906989-2f413806-7948-11e8-8bea-1279fc0ef4e3.png)

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment]
Please check this option, in your sunstone view:

https://github.com/OpenNebula/one/blob/5c072dae4ce3323579aa4d96b0f329e79101f8d3/src/sunstone/etc/sunstone-views/kvm/user.yaml#L739

**Comment by BcTpe4HbIu** [comment]
vnet-tab on /etc/one/sunstone-views/user.yaml is: 

```
    vnets-tab:
        panel_tabs:
            vnet_info_tab: true
            vnet_ar_list_tab: true
            vnet_leases_tab: true
            vnet_sg_list_tab: true
            vnet_vr_list_tab: true
            vnet_clusters_tab: false
        table_columns:
            - 0         # Checkbox
            - 1         # ID
            - 2         # Owner
            - 3         # Group
            - 4         # Name
            - 5         # Reservation
            - 6         # Cluster
            #- 7         # Bridge
            - 8         # Leases
            #- 9         # VLAN ID
            #- 10         # Labels
            #- 11        # Search data
        actions:
```

But in groupadmin.yaml there is only ID and Name:

```
    vnets-tab:
        panel_tabs:
            vnet_info_tab: false
            vnet_ar_list_tab: false
            vnet_leases_tab: true
            vnet_sg_list_tab: true
            vnet_vr_list_tab: false
            vnet_clusters_tab: false
        table_columns:
            - 0         # Checkbox
            - 1         # ID
            #- 2        # Name
            #- 3        # Owner
            - 4         # Group
            #- 5        # Reservation
            #- 6        # Cluster
            #- 7        # Bridge
            #- 8        # Leases
            #- 9        # VLAN ID
            #- 10       # Labels
            #- 11       # Search data
        actions:
```

That's the reason?
