### ISSUE TITLE
Marketplace Apps with more than one disk.

### ISSUE THREAD

**Issue by sergiojvg** [OpenNebula/one#2465]
**Description**
Allow marketplace apps to have several disks.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by baby-gnu** [comment]
We actually try to define a new appliance in our [appmarket-simple](https://github.com/OpenNebula/appmarket-simple) with several disks.

The [appmarket interface shows 2 `Files`](https://lab1.labs.eole.education/appliance/602f83ec-7f3b-42db-924c-d4cecc9a0caa) but when importing it in a opennebula 6.2 only the first one is downloaded.

**Comment by al3xhh** [comment]
This is already supported, you can have a VM template with multiple disks, you can check [this](https://docs.opennebula.io/6.2/management_and_operations/storage_management/marketapps.html).

> We actually try to define a new appliance in our [appmarket-simple](https://github.com/OpenNebula/appmarket-simple) with several disks.

In order to do that, please check [this example](https://github.com/OpenNebula/marketplace/blob/master/appliances/kvm/40e9da59-0171-4be5-a0e2-3a94a80bd724.yaml).

Closing this issue, if there is any bug related with this, please open a new issue.

**Comment by baby-gnu** [comment]
> This is already supported, you can have a VM template with multiple disks, you can check [this](https://docs.opennebula.io/6.2/management_and_operations/storage_management/marketapps.html).

Thanks @al3xhh, so if I understand correctly:

- I can create a VM app with a single `images:` key, it will download the image in my datastore and create the VM template according to `opennebula_template:`
- To create a VM several disks, I need
  1. create as many [disks without template](https://github.com/OpenNebula/marketplace/blob/e1defc4c90343ac465a6c40f33dc55e19b5c75b0/appliances/all/251b0578-6c47-4ba4-b184-dc6e873201a2.yaml) as I need
  2. reference thoses disks in my VM App YAML under `disks:` list and keep `images:` an empty list.
  
Right?

<details><summary>My VM app is providing several disks under <code>images:</code></summary>

```
---
name: eole3-k3s
version: 1.0.5
publisher: Pôle de Compétence Logiciels Libres
short_description: Base d’EOLE3 utilisant k3s
description: |-
  Module de base EOLE3 sur apline avec k3s

tags:
- pcll
- eole
- 3.0.0
- eolebase
- server
- kubernetes
- k3s

format: qcow2

creation_time: 1639386461

os-id: EOLE
os-release: '3.0.0'
os-arch: x86_64
hypervisor: KVM

# Compatibility with OpenNebula releases. Appliance will be
# offered only to OpenNebula clients with matching version!!
opennebula_version: 5.12, 6.0, 6.2

# The template for the appliance without disks and in YAML format
opennebula_template:
  context:
    network: 'YES'
    ssh_public_key: "$USER[SSH_PUBLIC_KEY]"
    report_ready: "YES"
    set_hostname: "$NAME"
    token: "YES"
  cpu: '2'
  vcpu: '4'
  graphics:
    listen: 0.0.0.0
    type: vnc
  memory: '4096'
  os:
    arch: x86_64
    sd_disk_bus: "scsi"
  logo: images/logos/eole.png
  sched_requirements: HYPERVISOR!=\"vcenter\"

logo: eole.png

images:
- name: eole3-k3s-alpine-3.14.2.qcow2
  url: https://lab1.labs.eole.education/images/eole3-k3s-alpine-3.14.2.qcow2
  type: OS
  dev_prefix: sd
  driver: qcow2
  size: 42949672960
  checksum:
    md5: 7f4164b62875a2fc2065b4b41021b047
    sha256: e2fd8cda317f6b52d2056da5db27219f1d3271f2924bcede7f679e2ac612a2ab
- name: DSK-50Go.qcow2
  url: https://lab1.labs.eole.education/images/DSK-50Go.qcow2
  type: OS
  dev_prefix: sd
  driver: qcow2
  size: 53687091200
  checksum:
    md5: f8baa0e00dcb25dbc3fdeb70a9bea2be
    sha256: 96285d8ccd4cddc30f9994f87be5a6944c3f5f1655faa4808065a1127486499b
```

The plural form of `images:` is confusing because I thought we could provide several of them.

For your example, the market place show no information about disks for [`custom via netboot.xyz` app](https://marketplace.opennebula.io/appliance/40e9da59-0171-4be5-a0e2-3a94a80bd724), which is quite disturbing.

But [our example](https://lab1.labs.eole.education/appliance/602f83ec-7f3b-42db-924c-d4cecc9a0caa) shows 2 `Files`.

I keep thinking that something is strange here.
