### ISSUE TITLE
Amazon EC2 driver bare betal support

### ISSUE THREAD

**Issue by laurencegill** [OpenNebula/one#3483]
I'd like to be able to deploy bare metal through opennebula in AWS London region, but the docs state only i3.metal is supported:

http://docs.opennebula.org/5.8/advanced_components/ddc/reference/provision/driver/ec2.html

i3.metal isn't available in London, only c/m/r.metal hosts are.  

Is the documentation correct, are these not supported?  They seem to be in the ec2_driver.conf file?

**Comment by al3xhh** [comment]
Hello @laurencegill 

DDC should work with any metal instances, but we only test it with i3.metal, because they were the only available instances when we worked on it.

I have made some tests with r5.metal, here you have the steps I followed and the results:

Provision template
-------------------------

```
---
name: london-provision
playbook: default

defaults:
  provision:
    driver: ec2
    ami: ami-7c141006
    cloud_init: true
    instancetype: r5.metal
    securitygroupsids: ****
    subnetid: ****
    ec2_access: ****
    ec2_secret: ****
    region_name: us-east-1
  connection:
    remote_user: centos
  configuration:
    opennebula_node_kvm_param_nested: true

cluster:
  name: london-cluster

hosts:
  - reserved_cpu: 100
    im_mad: kvm
    vm_mad: kvm
    provision:
      hostname: "<%= @name %>-host1"
```

Note: I deploy it in us, but the instance type is also available in London, also take in account that the ami you use must have **[ena](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html)** enabled.

Steps
--------

- Command to deploy: `oneprovision create simple.yaml -D --ping_retries 20 --ping_timeout 30` I added those **ping** options because aws metal instances take too long to have the OS up and running. You will have to wait until Ansible finishes to configure everything.
- After that, you need to wait until OpenNebula monitors the host, so you will see it on **ON** state.
- Then you have to change the default emulator, so edit the file `/etc/one/vmm_exec/vmm_exec_kvm.conf` and uncomment `EMULATOR = /usr/libexec/qemu-kvm` line.
- Restart OpenNebula, so changes take effect.
- Finally you are ready to deploy VMs on that hosts, it's a fully operational KVM host.
