### ISSUE TITLE
Support for SAML authentication

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#3824]
**Description**

Include support for SAML as auth backend:

  https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language

**Use case**

User management with SAML based products.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Reference: #620

**Comment by terafirmanz** [comment]
Just adding my formal vote for this. These days it is imperative modern apps support SSO using SAML or even better OpenID Connect.

**Comment by kvaps** [comment]
@terafirmanz I had success with configuring OpenID Connect and OpenNebula, it was required just a little change in sunstone #3592

**Comment by tipirk** [comment]
@kvaps hi
Can you share how you did it?

**Comment by kvaps** [comment]
Hey @tipirk just enable remote authentication method for sunstone:

https://github.com/OpenNebula/one/blob/213dada892dccda573d66a02cca2e299a879d80e/src/sunstone/etc/sunstone-server.conf#L81-L89 

make it listen `127.0.0.1` only:

https://github.com/OpenNebula/one/blob/213dada892dccda573d66a02cca2e299a879d80e/src/sunstone/etc/sunstone-server.conf#L30-L33

then run [keycloak-gatekeeper](https://github.com/keycloak/keycloak-gatekeeper) auth-proxy behind the sunstone.

I have configuration like this:

```yaml
listen: 0.0.0.0:80
redirection-url: http://opennebula.example.org
secure-cookie: false
#listen: 127.0.0.1:8080
#redirection-url: https://opennebula.example.org
discovery-url: https://keycloak.example.org/auth/realms/opennebula
client-id: opennebula
client-secret: 4830a502-ac61-4a83-b198-adc0690db15c
enable-refresh-tokens: true
encryption-key: ve8aiSa0aeB8ya5ni1auluay2ohp7ocu
upstream-url: https://opennebula.example.org/
resources: 
- uri: /*
```

Note you can use any Oauth2 provider with keycloak-gatekeeper (not only Keycloak server), but you still need to manually create users in OpenNebula.
