### ISSUE TITLE
LXD NUMA settings and pinning settings are broken

### ISSUE THREAD

**Issue by meier-rene** [OpenNebula/one#4033]
**Description**
Instantiation of a LXD container with NUMA settings and pinning enabled does not give expected results in container.

**To Reproduce**
Instantiate a lxd container with the following template settings:
```
TOPOLOGY = [
  CORES = "12",
  PIN_POLICY = "THREAD",
  SOCKETS = "2",
  THREADS = "2" ]
```
**Ignores one numa node** and **assigns only half of the desired CPUs**. Below the informations from the resulting container:

lxc config show one-889
```
architecture: x86_64
config:
  limits.cpu: 12,36,13,37,14,38,15,39,16,40,17,41,18,42,19,43,20,44,21,45,22,46,23,47
  limits.cpu.allowance: 4800%
  limits.memory: 256000MB
```

lstopo topo.png
![topo](https://user-images.githubusercontent.com/25176376/70426911-20f9ed00-1a74-11ea-852c-9e5f1cefa298.png)

**Expected behavior**
The assignment of CPUs should meet the defined template structure.

**Details**
 - Affected Component: Scheduler, container creation
 - Hypervisor: LXD
 - Version: 5.10

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches
