### ISSUE TITLE
LXD CPU limit config not being applied from template

### ISSUE THREAD

**Issue by ilhaan** [OpenNebula/one#4209]
**Description**
Setting the number of CPUs in an OpenNebula template when instantiating a new container does not work. 

**To Reproduce**
1. Launch LXD container on OpenNebula. Set "CPU" to 4. 
2. Once container is in "Running" state, VNC into container and run the following: 
```
grep -c processor /proc/cpuinfo
```
3. Output of the command will not match setting used in step 1 (output might be `1` - this seems to be coming from the default LXD profile used by OpenNebula. 

**Expected behavior**
I would expect the number of CPUs allocated to the LXD container to match the value used in the OpenNebula template used to launch the container. 

**Details**
 - Affected Component: LXD Containers
 - Hypervisor: LXD
 - Version: 5.10.1
 - LXD Version: 3.0.4 (snap installed) 

**Additional context**
In the following command line output, I have launched an LXD container (`one-14387`) via OpenNebula WebUI where the CPU setting is 4 in the template. I have also logged into the host where the container has been launched to execute `lxc` commands: 
```
user@server:~# lxc exec one-14387 -- grep -c processor /proc/cpuinfo 
1
```
As the output shows, the setting from the template did not take effect. The `1` seems to be from the `default` LXD profile that OpenNebula creates upon installation of the `opennebula-node-lxd` package (note that I also have `opennebula-lxd-snap` installed): 
```
user@server:~# lxc profile show default 
config:
  limits.cpu: "1"
  limits.cpu.allowance: 50%
  limits.memory: 512MB
  security.idmap.base: "100000"
  security.idmap.isolated: "true"
  security.idmap.size: "65536"
description: Default LXD profile  for OpenNebula
devices:
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/one-14387
```
This is inconsistent with documentation [here](https://docs.opennebula.org/5.10/deployment/open_cloud_host_setup/lxd_driver.html#profiles) which states: 
> ...template will override any matching key with the profile. If the profile is not found on the node, the default profile will be applied and an error will appear on the VM log.

I verified that the `user.xml` that OpenNebula applies (source code [here](https://github.com/OpenNebula/one/blob/d0e8d214c61533f1937f59021d2c2a725a43d377/src/vmm_mad/remotes/lxd/deploy#L86)) is passed to the container as shown below (output truncated for brevity): 
```
user@server:~# lxc config show one-14387
architecture: x86_64
config:
  limits.cpu.allowance: 400%
  limits.memory: 8192MB
  security.nesting: "yes"
  security.privileged: "yes"
  user.xml: |
    ......<CPU><![CDATA[4]]></CPU>........
```

However, manually setting the CPU limit seems to be working fine: 
```
user@server:~# lxc config set one-14387 limits.cpu 4 
user@server:~# lxc exec one-14387 -- grep -c processor /proc/cpuinfo 
4
```
This issue does not occur for any other config being set in the template. Memory was set to 8GB in the template for `one-14387` and seems to be correct without manual updating as shown below: 
```
user@server:~# lxc exec one-14387 -- grep MemTotal /proc/meminfo 
MemTotal:        8000000 kB
```

How do I ensure CPU setting from the template is applied to the container? 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches
