### ISSUE TITLE
Provision template dynamic inputs

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4216]
**Description**

Provision template is YAML file with little dynamic introduced by the (undocumented) ERB expressions within the values. The expressions allow to access the structure with processed provision objects. It might be useful to support parameters, which could be passed from command line or template and could be referenced via ERB as well.

For example:

```yaml
--- base.yaml

inputs:
  ### --- Parameters without defaults, must be provided other way
  provider_token: NULL
  provider_project: NULL
  ### --- Parameters with defaults
  provider_facility: ams1
  provider_plan: baremetal_0
  provider_os: centos_7

defaults:
  provision:
    ### --- Values reference to the parameters specified above
    packet_token: '<%= @inputs["provider_token"] %>'
    packet_project: '<%= @inputs["provider_project"] %>'
    facility: '<%= @inputs["provider_region"] %>'
    plan: '<%= @inputs["provider_plan"] %>'
    os: '<%= @inputs["provider_os"] %>'
    driver: packet
...
```

When such template is executed, it's obviously missing `provider_token` and `provider_project` parameters, as the ones specified in the template are NULLs. Such provision should fail, for example:

```
$ oneprovision create base.yaml
ERROR: Missing input parameters provider_token, provider_project
```

The parameters could be provided 2 ways:

- on the command line

```
$ oneprovision create base.yaml \
    --input provider_project=XXX \
    --input provider_token=XXX
```

- via template with inheritance:

```yaml
--- override.yaml

inputs:
  provider_token: XXX
  provider_project: XXX

extends: base.yaml
```

Same as with any other sections (mainly referring to the defaults), the data even in the parameters are merged and on conflicting parameters, the parent template overrides the values of template it extends. Values provided on command line have even higher priority than those in the template.

Steps:
- support  "inputs" section (more suitable name could be used - params?, parameters?)
    - accessed via ERB
    - with template inheritance
- oneprovision create 
    - command-line parameters to pass inputs
    - fail on missing values (NULLs)

**Use case**

Provision templates, which can be easily customized without the need to change / hack the base template itself.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment]
Types of inputs will be the same as the user inputs understood by Sunstone at the moment.

Example:

```
  hosts:
    - count:
        - description: "Number of hosts of this provision
        - type: "range"
        - min_value: 1
        - max_value: 100
        - default: "4"
        - value: ""
    - reserved_cpu:

  networks:
    - iprange:
        - description: "CIDR range for vnet"
        - type: "text"
        - default: "192.168.1.1/24"
        - value: ""
```
