### ISSUE TITLE
Provision objects count

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#4217]
**Description**
Provision template precisely defines how the cluster will look like, which objects and how many of them. That needs to precisely know cluster sizing, number of hosts. E.g., in this case we create a cluster of just 2 hosts:

```yaml
hosts:
  - reserved_cpu: 100
    im_mad: kvm
    vm_mad: kvm
    provision:
      hostname: "myhost1"
  - reserved_cpu: 100
    im_mad: kvm
    vm_mad: kvm
    provision:
      hostname: "myhost2"
```

It would be nice if objects could have a parameter to indicate number of such objects to create, the example above could be reduced to:

```yaml
hosts:
  - reserved_cpu: 100
    im_mad: kvm
    vm_mad: kvm
    provision:
      hostname: "myhost<%= @a_suitable_unique_identifier_of_object %>"
    count: 2
```

or, ideally could be also parameterized via user inputs (#4216):

```yaml
inputs:
  hosts_count: 2

hosts:
  - reserved_cpu: 100
    im_mad: kvm
    vm_mad: kvm
    provision:
      hostname: "myhost<%= @a_suitable_unique_identifier_of_object %>"
    count: "<%= @inputs['hosts_count'] %>"
```

Just an idea, needs to be designed (e.g., can't be the "count" name confused with regular object template parameters?).

**Use case**
Provision templates, which can be easily customized without the need to change / hack the base template itself.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches
