### ISSUE TITLE
When datastore have no tabs in shouldn't be clickable

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4320]
**Description**
![image](https://user-images.githubusercontent.com/7556217/76084713-d45d7980-5fb0-11ea-812c-a09e196afa9e.png)

**To Reproduce**
* Set
    ```yaml
    datastores-tab:
        panel_tabs:
            datastore_info_tab: false
            datastore_image_tab: false
            datastore_clusters_tab: false
    ```

* Go to datastores tab
* Click on some datastore

**Expected behavior**
Sunstone shouldn't shouldn't open empty page

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.10.2

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches
