### ISSUE TITLE
Can't disable NUMA tab for VM templates

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4323]
**Description**
Sunstone views are not allowing to disable NUMA tab 

**To Reproduce**

* Specify:
    ```yaml
    templates-tab:
        actions:
            Template.numa: true
        template_creation_tabs:
            numa: true
    ```
* Try to create new template

**Expected behavior**
NUMA tab is disabled

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.10.2

**Additional context**
https://github.com/OpenNebula/one/blob/2134aabb9dd91bd1223e592234ddab90ed53158c/src/sunstone/etc/sunstone-views/mixed/admin.yaml#L276

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches
