### ISSUE TITLE
Sunstone login not working for newly created user

### ISSUE THREAD

**Issue by TheTesla** [OpenNebula/one#5009]
**Description**
Users created via sunstone or via oneuser create can't login via sunstone interface.

**To Reproduce**
Install opennebula 5.12.0.1 with sunstone, node and sqlite3 backend on ubuntu 18.04.
Login example.org:9869 as oneadmin.
Create user with with public authentication.
oneadmin logout.
Login with newly created useraccount and given password.
"Invalid username or password"

**Expected behavior**
User should get authenticated. No error message.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: n. a.
 - Version: 5.12.0.1

**Additional context**
user is sometime created with clear text password, sometimes with hash, as seen in the sqlite3 db and oneuser show.

Ansible task:
```yml
- name: Distribution
  debug: 
    msg: "{{ ansible_distribution }}"

- name: Distribution version
  debug: 
    msg: "{{ ansible_distribution_version}}"

- name: Distribution major version
  debug: 
    msg: "{{ ansible_distribution_major_version }}"

- name: Install Dependencies - Add Ubuntu standard repos
  shell: |
    add-apt-repository main
    add-apt-repository restricted
    add-apt-repository universe
    add-apt-repository multiverse 

- name: Install Opennebula - Add repo key
  apt_key: 
    url: "https://downloads.opennebula.org/repo/repo.key"
    state: present 

- name: Install Opennebula - Add repo
  apt_repository:
    repo: "deb https://downloads.opennebula.io/repo/{{ one_version }}/{{ ansible_distribution }}/{{ ansible_distribution_version}} stable opennebula"
    state: present
    update_cache: yes

- name: Install Opennebula - Install packages
  package:
    name:
      - opennebula 
      - opennebula-sunstone 
      - opennebula-gate 
      - opennebula-flow
    state: latest
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches
