### ISSUE TITLE
Disappeared top buttons in Sunstone 6.6

### ISSUE THREAD

**Issue by evmnaumov** [OpenNebula/one#6087]
**Description**
Disappeared top buttons in Sunstone 6.6. For example, unable to "Enable" or "Disable" marketplace

**Expected behavior**

**Details**
 - Affected Component: Sunstone
 - Version: 6.6 stable

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
Hi, Apologies for the inconvenience.
This issue is happening as there are missing the following lines in the YAML configuration files.
```
MarketPlace.enable: true
MarketPlace.disable: true
```
Please add them to the views that you want to enable this functionality.

For example, you can add it to: `/etc/one/sunstone-views/mixed/admin.yaml` under the `marketplaces-tab` -> `actions`

```
marketplaces-tab:
    panel_tabs:
      marketplace_info_tab: true
      marketplace_apps_tab: true
    table_columns:
      - 0 # Checkbox
      - 1 # ID
      - 2 # Name
      - 3 # Owner
      - 4 # Group
      - 5 # Capacity
      - 6 # Apps
      - 7 # Driver
      - 8 # Zone
      #- 9        # Labels
      #- 10       # Search data
    actions:
      MarketPlace.refresh: true
      MarketPlace.create_dialog: true
      MarketPlace.update_dialog: true
      MarketPlace.rename: true
      MarketPlace.chown: true
      MarketPlace.chgrp: true
      MarketPlace.chmod: true
      MarketPlace.delete: true
      MarketPlace.lockU: true
      MarketPlace.unlock: true
      MarketPlace.edit_labels: true
      MarketPlace.menu_labels: true
      MarketPlace.enable: true
      MarketPlace.disable: true
```

We will close this issue after this comment but feel free to comment again on it if the provided solution doesn't work.
