### ISSUE TITLE
Avoid libvirt deactivating on AlmaLinux9 on reboot

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#6143]
**Description**
In AlmaLinux9 when a KVM host is restarted, libvirtd disables itself during system startup.

**To Reproduce**
Add an OpenNebula KVM host that's based on AlmaLinux9, then restart it. There is a chance you'll experience auto-deactivation of the libvirtd service: `28 Feb 13 07:38:18 host1 systemd[1]: libvirtd.service: Deactivated successfully.`

**Expected behavior**
The libvirtd service should not be deactivating itself.

**Details**
 - Affected Component: KVM Host, AlmaLinux9
 - Hypervisor: KVM
 - Version: 6.4+

**Comment by xorel** [comment]
Can not reproduce.
As long as virtproxyd.socket is enabled  and running then also new modular libvirt is working.


```
cat /usr/lib/systemd/system-preset/90-default.preset
...
 # Compatibility with libvirtd sockets for old clients and expose TCP sockets
enable virtproxyd.socket
```
So at least in AlmaLinux 9.1
```
rpm -qf /usr/lib/systemd/system-preset/90-default.preset
almalinux-release-9.1-1.9.el9.x86_64
```

**Comment by sk4zuzu** [comment]
After further investigation we now know what is going on! :smiling_face_with_tear: 

Please take a look [here](https://fedoraproject.org/wiki/Changes/LibvirtModularDaemons#Detailed_Description) ->

> The work will primarily involve changes in the systemd presets related to libvirt. Currently the Fedora systemd presets enable libvirtd.service. While libvirtd does support socket activation this is not used during host startup, because the libvirtd daemon needs to be fully started in order to auto-start QEMU guests that may be configured. The current libvirtd.service uses a timeout, however, that causes libvirtd to shutdown after 2 minutes if no VM is running.

The automatic deactivation we've observed is a feature of the new modular libvirt.

Unfortunately OpenNebula currently cannot successfully deal with that, so it's required to disable systemd socket activation, please take a look [here](https://libvirt.org/manpages/libvirtd.html#system-socket-activation).

Steps we suggest as a workaround for AlmaLinux9 running OpenNebula ->

1. Mask virtqemud and its sockets
    ```shell
    systemctl mask virtqemud{.service,.socket,-admin.socket,-ro.socket} --now
    ```
2. Mask libvirtd's sockets
    ```shell
    systemctl mask libvirtd{.socket,-admin.socket,-ro.socket,-tcp.socket,-tls.socket} --now
    ```
3. Override libvirtd's systemd unit and revert the `Environment=LIBVIRTD_ARGS="--timeout 120"` setting
    ```shell
    $ install -o root -g root -D /dev/fd/0 /etc/systemd/system/libvirtd.service.d/override.conf <<'EOF'
    [Service]
    Environment=LIBVIRTD_ARGS=""
    EOF
    ```
4. Run `systemctl daemon-reload`

:ok_hand:

**Comment by tinova** [comment]
Add a note in the Platform notes https://docs.opennebula.io/6.6/intro_release_notes/release_notes/platform_notes.html#front-end-platform-notes

**Comment by sk4zuzu** [comment]
When after steps 1, 2, 3, 4 your OpenNebula instance fails to successfully monitor the host, then you might want to check if there are stale virtqemud sockets in `/var/run/libvirt/`. If such socket files are present and virtqemud is disabled and stopped, then running virsh is likely to fail, because of the invalid socket files cannot be openned. You might want to run `virsh -r -c qemu:///system capabilities` on the host directly to confirm. As a workaround you can delete all virtqemud socket files.

**Comment by feldsam** [comment]
Interesting. In OL9 for a few years we use just following ansible tasks to setup nodes. Mainly this is from RHEL9 docs.


```
- name: Start and enable virtd
  shell: "for drv in qemu network nodedev nwfilter secret storage interface; do systemctl enable --now virt${drv}d{,-ro,-admin}.socket; done"
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '9'
  tags: libvirt

- name: Copy virtproxyd config
  copy:
    src: etc/libvirt/libvirtd.conf
    dest: /etc/libvirt/virtproxyd.conf
    mode: 0644
  notify: restart virtproxyd-tcp
  tags: libvirt

- name: Enable and start virtproxyd-tcp
  service:
    name: virtproxyd-tcp.socket
    state: started
    enabled: yes
  tags: libvirt

- name: Copy qemu config
  copy:
    src: etc/libvirt/qemu.conf
    dest: /etc/libvirt/qemu.conf
    mode: 0644
  notify: restart virtd
  tags:
    - libvirt
    - qemu

- name: allow oneadmin group to always use libvirt
  copy:
    src: polkit-rules/50-libvirt.rules
    dest: /etc/polkit-1/rules.d/50-libvirt.rules
    mode: 0644
  notify: restart polkit
  tags:
    - libvirt
    - polkit
```

handler
```
- name: restart virtd
  shell: "for drv in qemu network nodedev nwfilter secret storage interface; do systemctl restart virt${drv}d{,-ro,-admin}.socket; done"
```
