### ISSUE TITLE
Wrong configuration for FreeMemory10 on file `/etc/one/prometheus/rules.yml`

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6225]
**Description**
After configured the alertmanager service on new monitoring solution, there are predefined rules for this service in the file `/etc/one/prometheus/rules.yml`. The rule `FreeMemory10` has a wrong expression for the calculation of the Free Memory %. Is firing the alert when the memory is >= 10% and should be when is <=10%.

**To Reproduce**
Configure the alertmanager service and the prometheus service as described in the official documentation:
- <https://docs.opennebula.io/6.6/management_and_operations/monitor_alert/alerts.html>

**Expected behavior**
This rule should be active only when the Free Memory is below the 10% and not above of it.

**Solution**

```bash
cp /etc/one/prometheus/rules.yml{,.orig} && \
nano +20 /etc/one/prometheus/rules.yml
```

Replace the original line with the following one:

```bash
    expr: ((node_memory_MemFree_bytes * 100) / node_memory_MemTotal_bytes) <= 10
```

> **NOTE**<br />
>
> The original line is this one: <br />
>
> ```bash
>     expr: 100 - ((node_memory_MemFree_bytes * 100) / node_memory_MemTotal_bytes) <= 10
> ```
>

Restart the services in order to apply the changes:

```bash
systemctl restart opennebula-prometheus.service
```

**Details**
 - Affected Component: [Alertmanager]
 - Hypervisor: [KVM]
 - Version: [6.6.2]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by Franco-Sparrow** [comment]
@rsmontero @sk4zuzu Sorry guys but this is just not working yet.

![imagen](https://github.com/OpenNebula/one/assets/56793015/dd9b4811-34f0-409b-ade0-4b0f4386955b)

Using default `/etc/one/prometheus/prometheus.yml` generated by `/usr/lib/one/opennebula_exporter/opennebula_vm_collector.rb`:

```yaml
---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093
rule_files:
- rules.yml
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - orchestrator1:9090
    labels:
      hostname: orchestrator1
- job_name: opennebula_exporter
  static_configs:
  - targets:
    - 127.0.0.1:9925
- job_name: node_exporter
  static_configs:
  - targets:
    - 127.0.0.1:9100
  - targets:
    - ON-DEV-N1:9100
    labels:
      one_host_id: '0'
- job_name: libvirt_exporter
  static_configs:
  - targets:
    - ON-DEV-N1:9926
    labels:
      one_host_id: '0'
```

And issue temporarily disappear after restart services on orchestrator:

```bash
systemctl restart opennebula-prometheus.service opennebula-exporter.service opennebula-node-exporter.service opennebula-alertmanager.service
```

And same on node:

```bash
systemctl restart opennebula-libvirt-exporter.service opennebula-node-exporter.service
```

Packages are on 6.6.3 and all services are UP and RUNNING.
