### ISSUE TITLE
CLI listing formatting ignored when passing --search

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#6511]
**Description**
When `--search` is added to the cli listing command, ex `onevm list`, the formatting that can be used with `--json` or `--yaml` will be ignored and the default listing will be issued.

**To Reproduce**
For example

```
onevm list --yaml --no-pager --search LXD_SECURITY_PRIVILEGED
   ID NAME                                                 STAT IP
10531 ubuntu_desktop-10531                                 runn 172.20.0.5
10512 pe_dev                                               runn 172.20.0.12
 8705 bots                                                 runn 172.20.0.20
```

The filtering is correct but the output isn't

**Expected behavior**

Correct filtering with formatted output

```yaml
---
---
VM_POOL:
  VM:
  - ID: '10531'
    UID: '5'
    GID: '1'
    UNAME: dclavijo
    GNAME: users
    NAME: ubuntu_desktop-10531
    LAST_POLL: '0'
    STATE: '3'
    LCM_STATE: '3'
    RESCHED: '0'
    STIME: '1706833993'
    ETIME: '0'
    DEPLOY_ID: 52d54aa7-255d-4031-aa5f-631308af4dd4
    LOCK:
      LOCKED: '1'
    TEMPLATE:
      CPU: '1'
      MEMORY: '2048'
      VCPU: '2'
      DISK:
      - DISK_ID: '0'
        DATASTORE: default
        DATASTORE_ID: '1'
        IMAGE: ubuntu_desktop-disk-0
        IMAGE_ID: '308'
        SIZE: '10240'
        TYPE: FILE
        CLONE: 'NO'
        CLONE_TARGET: SYSTEM
        LN_TARGET: NONE
        DISK_SNAPSHOT_TOTAL_SIZE: '0'
      NIC:
      - IP: 172.20.0.5
        MAC: 02:00:ac:14:00:05
        NETWORK: service
        NETWORK_ID: '147'
        NIC_ID: '0'
        SECURITY_GROUPS: '0'
      GRAPHICS:
        LISTEN: 0.0.0.0
        PORT: '16431'
        RANDOM_PASSWD: 'NO'
        TYPE: VNC
    MONITORING: {}
    USER_TEMPLATE: {}
    HISTORY_RECORDS:
      HISTORY:
        OID: '10531'
        SEQ: '0'
        HOSTNAME: localhost
        HID: '0'
        CID: '0'
        DS_ID: '100'
        VM_MAD: kvm
        TM_MAD: qcow2
        ACTION: '0'
  - ID: '10512'
    UID: '5'
    GID: '1'
    UNAME: dclavijo
    GNAME: users
    NAME: pe_dev
    LAST_POLL: '0'
    STATE: '3'
    LCM_STATE: '3'
    RESCHED: '0'
    STIME: '1706113403'
    ETIME: '0'
    DEPLOY_ID: 63450b0b-507e-46d9-93d3-57c926492940
    TEMPLATE:
      CPU: '12'
      MEMORY: '8192'
      VCPU: '12'
      DISK:
      - DISK_ID: '0'
        DATASTORE: default
        DATASTORE_ID: '1'
        IMAGE: Ubuntu 22.04
        IMAGE_ID: '200'
        SIZE: '40960'
        TYPE: FILE
        CLONE: 'YES'
        CLONE_TARGET: SYSTEM
        LN_TARGET: NONE
        DISK_SNAPSHOT_TOTAL_SIZE: '0'
      NIC:
      - IP: 172.20.0.12
        MAC: 02:00:ac:14:00:0c
        NETWORK: service
        NETWORK_ID: '147'
        NIC_ID: '0'
        SECURITY_GROUPS: '0'
      GRAPHICS:
        LISTEN: 0.0.0.0
        PORT: '16412'
        TYPE: VNC
    MONITORING: {}
    USER_TEMPLATE: {}
    HISTORY_RECORDS:
      HISTORY:
        OID: '10512'
        SEQ: '3'
        HOSTNAME: localhost
        HID: '0'
        CID: '0'
        DS_ID: '100'
        VM_MAD: kvm
        TM_MAD: qcow2
        ACTION: '0'
    UID: '5'
    GID: '1'
    UNAME: dclavijo
    GNAME: users
    NAME: ldap
    LAST_POLL: '0'
    STATE: '9'
    LCM_STATE: '0'
    RESCHED: '0'
    STIME: '1697723517'
    ETIME: '0'
    DEPLOY_ID: 1c05031e-67da-493c-b33d-3c0241a04558
    TEMPLATE:
      CPU: '0.5'
      MEMORY: '3072'
      VCPU: '2'
      DISK:
      - DISK_ID: '0'
        DATASTORE: default
        DATASTORE_ID: '1'
        IMAGE: ubuntu2204
        IMAGE_ID: '220'
        SIZE: '25600'
        TYPE: FILE
        CLONE: 'YES'
        CLONE_TARGET: SYSTEM
        LN_TARGET: NONE
        DISK_SNAPSHOT_TOTAL_SIZE: '0'
      NIC:
      - IP: 172.20.0.33
        MAC: 02:00:ac:14:00:21
        NETWORK: service
        NETWORK_ID: '147'
        NIC_ID: '0'
        SECURITY_GROUPS: '0'
      - IP: 192.168.150.1
        MAC: 02:00:c0:a8:96:01
        NETWORK: private-ubuntu2204-func-6-99-xkcdv
        NETWORK_ID: '3609'
        NIC_ID: '1'
        SECURITY_GROUPS: '0'
      GRAPHICS:
        LISTEN: 0.0.0.0
        TYPE: VNC
    MONITORING: {}
    USER_TEMPLATE: {}
    HISTORY_RECORDS:
      HISTORY:
        OID: '9943'
        SEQ: '0'
        HOSTNAME: localhost
        HID: '0'
        CID: '0'
        DS_ID: '100'
        VM_MAD: kvm
        TM_MAD: qcow2
        ACTION: '5'
  - ID: '8705'
    UID: '5'
    GID: '1'
    UNAME: dclavijo
    GNAME: users
    NAME: bots
    LAST_POLL: '0'
    STATE: '3'
    LCM_STATE: '3'
    RESCHED: '0'
    STIME: '1679075588'
    ETIME: '0'
    DEPLOY_ID: 388f17a6-4ff1-4589-9625-5b8303241928
    LOCK:
      LOCKED: '1'
    TEMPLATE:
      CPU: '1'
      MEMORY: '512'
      VCPU: '2'
      DISK:
      - DISK_ID: '0'
        DATASTORE: default
        DATASTORE_ID: '1'
        IMAGE: alpine_317
        IMAGE_ID: '236'
        SIZE: '256'
        TYPE: FILE
        CLONE: 'YES'
        CLONE_TARGET: SYSTEM
        LN_TARGET: NONE
        DISK_SNAPSHOT_TOTAL_SIZE: '0'
      NIC:
      - IP: 172.20.0.20
        MAC: 02:00:ac:14:00:14
        NETWORK: service
        NETWORK_ID: '147'
        NIC_ID: '0'
        SECURITY_GROUPS: '0'
      GRAPHICS:
        LISTEN: 0.0.0.0
        PORT: '14605'
        TYPE: vnc
    MONITORING: {}
    USER_TEMPLATE: {}
    HISTORY_RECORDS:
      HISTORY:
        OID: '8705'
        SEQ: '4'
        HOSTNAME: localhost
        HID: '0'
        CID: '0'
        DS_ID: '100'
        VM_MAD: kvm
        TM_MAD: qcow2
        ACTION: '0'
```

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler, or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)
