### ISSUE TITLE
DUPLICATED ISSUE DELETE ME - default_groupadmin not working on FSunstone (FireEdge)

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6904]
## Description

Default view for groupadmins cant load this view for them on FSunstone. Is not able to load `default_groupadmin`. RSunstone can successfully load this view for default admins.

## To Reproduce

1-Create a user and group and make this user admin of its own group (Default behavior when create users from OpenNebula Tenants for WHMCS).
2-Login into the cloud and the default view will not be the groupadmin view.

`roles/install_opennebula/files/fsunstone-views.yaml`
```
# This file describes which Sunstone views are available according to the
# primary group a user belongs to

# Specify the filename for a custom logo to be used in the UI.
# Acceptable formats include: .jpg, .jpeg, .png.
# Ensure the filename adheres to the pattern: [a-zA-Z0-9-_]+.(jpg|jpeg|png)
# Example:
#
# logo: custom_logo.png

#logo: images/opennebula-5.0.png
groups:
    oneadmin:
        - admin
        - group_admin
        - advanced
        - simple
default:
    - advanced
    - simple
default_groupadmin:
    - group_admin
    - advanced
    - simple
labels_groups:
    default:

# Name and description of each view.
#
# More views could be added creating a new object under views attribute.
# Example:
#   customview:
#     name: Name of the custom view
#     description: Description of the custom view

views:
  admin:
    name: groups.view.admin.name
    description: groups.view.admin.description
  group_admin:
    name: groups.view.group_admin.name
    description: groups.view.group_admin.description
  advanced:
    name: groups.view.advanced.name
    description: groups.view.advanced.description
  simple:
    name: groups.view.simple.name
    description: groups.view.simple.description
```

## Expected behavior

Login int the cloud with a group admin user, and default view should be the configured view for group admin.

## Details
 - Affected Component: [FSunstone]
 - Hypervisor: [KVM]
 - Version: [6.10.2]

## Additional context

![Image](https://github.com/user-attachments/assets/05a97635-d797-4c39-9df3-c1c82e4e4dcc)

![Image](https://github.com/user-attachments/assets/0cebeba7-53fd-4903-ad2b-dd5cf130562d)

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)
